### ISSUE TITLE
[Automated Bug Report] still boss music after play again (oropouche - Monday, July 18, 2022 6:00 PM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#24]
Bug submitted by: oropouche

App Version Demo_0.0.2

## Bug description

still boss music after play again boss crab

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_18_18_00_51_92372.png)

<details><summary>Log File</summary>

Joystick reconnected ("Controller (XBOX 360 For Windows)").
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Steam Initialised
Added player 0 on device XInputControllerWindows
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 0
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 1
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 2
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 3
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 4
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 5
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
bossWaveIntroListener
Boss waiting for intro done
bossWaveIntroDone
Boss starting brain
Start pestle anim
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Start pestle anim
Launching wave 0

</details>

**Comment by GieziJo** [comment]
Reset music on level reload
