### ISSUE TITLE
[Automated Bug Report] can't purchase cards in store (oropouche - Monday, July 18, 2022 6:40 PM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#26]
Bug submitted by: oropouche

App Version Demo_0.0.2

## Bug description

can't make any purchase and top cards for selection are missing

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_18_18_40_41_71318.png)

<details><summary>Log File</summary>

Joystick reconnected ("Controller (XBOX 360 For Windows)").
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Reference for HermitShells.Shell.Cards.ShellCard with ID 3492353212659582782 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 6878191496673844910 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Steam Initialised
Added player 0 on device XInputControllerWindows
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 0
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 1
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 2
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 3
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 4
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Launching wave 5
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
bossWaveIntroListener
Boss waiting for intro done
bossWaveIntroDone
Boss starting brain
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Start pestle anim
Got here
System.Collections.Generic.List`1[Enemies.MiniCrab.EnemyDie_MiniCrab]
LEVEL DONE
got here
Added player 0 on device XInputControllerWindows
NullReferenceException: Object reference not set to an instance of an object
InvalidOperationException: Sequence contains no elements
InvalidOperationException: Sequence contains no matching element
Launching wave 0
NullReferenceException: Object reference not set to an instance of an object
There can be only one active Event System.

</details>

**Comment by GieziJo** [comment]
Should be solved by consolidating workflow, leaving open in case it shows up again
