### ISSUE TITLE
[Automated Bug Report] Shell selection data not loaded (Jo - Monday, July 25, 2022 4:12 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#36]
Bug submitted by: Jo

App Version Demo_0.0.3

## Error Message:

Saving Prefab to immutable folder is not allowed: Packages/ch.giezi.tools.githubissuebugreporter/Runtime/Resources/BugReporter.prefab

## Bug description

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_04_12_28_40591.png)

<details><summary>Log File</summary>

FMOD Studio: Creating editor system instance
FMOD: Cache updated.
FMOD: Cache updated.
Reference for HermitShells.Shell.Cards.ShellCard with ID 8325785880414564486 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 3358803981040870919 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 3358803981040870919 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 8325785880414564486 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Steam Initialised
Added player 0 on device Keyboard
Should not grab hot control with an active capture
Should not be capturing when there is a hotcontrol
Saving Prefab to immutable folder is not allowed: Packages/ch.giezi.tools.githubissuebugreporter/Runtime/Resources/BugReporter.prefab
Removed player 0 on device Keyboard
Added player 0 on device Keyboard

</details>

**Comment by GieziJo** [comment]
Error with easy save 3
