### ISSUE TITLE
[Automated Bug Report] Menu Selection Indicator Points to Multiple Items (DrJexter - Monday, July 25, 2022 6:03 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#37]
Bug submitted by: @dustin-spivey

App Version Demo_0.0.3

## Bug description

With mouse and keyboard when I hover over another menu item it shows the selection icon on that item as well as whatever item was most recently selected with the arrow keys. To get a selection arrow to show up with the mouse is also very difficult, it seems as if I have to be on very specific parts of the words. 

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_06_03_30_94800.png)

**Comment by GieziJo** [comment]
Mouse inputs disabled for now.
