### ISSUE TITLE
[Automated Bug Report] Can't submit a bug from the menu screen (DrJexter - Monday, July 25, 2022 6:06 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#38]
Bug submitted by: @dustin-spivey

App Version Demo_0.0.3

## Bug description

While the menu is up I can not access the bug screen, I have to close the menu to enter the bug lof

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_06_06_41_48042.png)

**Comment by GieziJo** [comment]
The two systems clash, not ideal. Both use Time.timeScale but don't directly communicate.
Not sure how to fix short term, but should be kept in mind for further playtesting down the line.
