### ISSUE TITLE
[Automated Bug Report] Menu Item Stays Highlighted (DrJexter - Monday, July 25, 2022 6:14 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#40]
Bug submitted by: @dustin-spivey

App Version Demo_0.0.3

## Bug description

If I select any menu item with mouse that item stay highlighted in the menu

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_06_14_53_6047.png)

**Comment by GieziJo** [comment]
Disabling mouse for now, but need to move buttons from animation to custom events
