### ISSUE TITLE
[Automated Bug Report] Hermit Dissapears When Spacebar is Hit (DrJexter - Monday, July 25, 2022 6:23 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#42]
Bug submitted by: @dustin-spivey

App Version Demo_0.0.3

## Bug description

Space bar makes Hermit dissapear. If I enter and exit the menu, Hermit will reappear.

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_06_23_51_96170.png)

**Comment by GieziJo** [comment]
By design, but changing key
