### ISSUE TITLE
[Automated Bug Report] Can't seem to enter the intro level (DrJexter - Monday, July 25, 2022 6:42 AM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#44]
Bug submitted by: @dustin-spivey

App Version Demo_0.0.3

## Bug description

No idea how to enter the intro level with mouse/keyboard. I tried "Enter" while next to Meridith but no luck

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_25_06_42_52_63011.png)

**Comment by GieziJo** [comment]
Adding key hint
