### ISSUE TITLE
[Automated Bug Report] no enemies spawning in eel level (Oropouche - Wednesday, July 27, 2022 3:37 PM)

### ISSUE THREAD

**Issue by EarlyCoffeeGames** [EarlyCoffeeGames/Hermit-Issues#49]
Bug submitted by: Oropouche

App Version Demo_0.0.2

## Bug description

no wave announcement and no enemies spawning

![BugShot](https://raw.githubusercontent.com/EarlyCoffeeGames/Hermit-Issues-Screenshots/Screenshots/Screenshots/2022_07_27_15_37_22_38162.png)

<details><summary>Log File</summary>

Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Reference for HermitShells.Shell.Cards.ShellCard with ID 4250951367114904773 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 7480009760111220819 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 7480009760111220819 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4250951367114904773 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Steam Initialised
Added player 0 on device XboxOneGampadMacOSWireless
Launching wave 0
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Calling Animator.GotoState on Synchronize layer
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Added player 0 on device XboxOneGampadMacOSWireless
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Unable to add the requested character to font asset [Hermit anUnderwaterTale SDF]'s atlas texture. Please make the texture [Hermit anUnderwaterTale SDF Atlas] readable.
Reference for HermitShells.Shell.Cards.ShellCard with ID 4592682204227815971 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 1979503465156992647 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4186764587237382179 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4046253400272199798 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 2983235381885898193 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 8385286213825205409 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 6045461429501666772 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 1414694621723986814 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 8076248927815538605 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 1979503465156992647 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4592682204227815971 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4046253400272199798 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 6045461429501666772 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 4186764587237382179 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Reference for HermitShells.Shell.Cards.ShellCard with ID 8076248927815538605 could not be found in Easy Save's reference manager. If you are loading objects dynamically (i.e. objects created at runtime), this warning is expected and can be ignored.
<i>To disable warnings from Easy Save, go to Window > Easy Save 3 > Settings, and uncheck 'Log Warnings'</i>
Added player 0 on device XboxOneGampadMacOSWireless
NullReferenceException: Object reference not set to an instance of an object
InvalidOperationException: Sequence contains no elements
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

</details>

**Comment by GieziJo** [comment]
Old version
